name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
    
    - name: Download dependencies
      run: go mod tidy
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build binary
      run: go build -o imgstore
    
    - name: Test CLI
      run: |
        ./imgstore || true  # Expected to fail without args
        echo "CLI test completed"

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Download dependencies
      run: go mod tidy
    
    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o imgstore-linux-amd64
        GOOS=windows GOARCH=amd64 go build -o imgstore-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o imgstore-darwin-amd64